---
# Collect junos facts
- name: Gather Junos-specific facts - PRE-UPGRADE
  junipernetworks.junos.junos_facts:
    gather_subset:
      - hardware        # Hardware-related facts like chassis info
      - config         # Configuration information
      - interfaces     # Interface details
      - default         # default values
  register: junos_facts
  ignore_errors: true
    
- name: Display gathered Junos facts
  ansible.builtin.debug:
    var: junos_facts.ansible_facts