---
# Main tasks
- name: Import build-cfg-file tasks
  ansible.builtin.import_tasks: build-cfg-file.yml
  when: isolation # Tasks take place during isolation stage and not repeated in normalization stage.

- name: Import traffic isolation tasks
  ansible.builtin.import_tasks: traffic-isolation.yml
  when: isolation

- name: Import traffic normalization tasks
  ansible.builtin.import_tasks: traffic-normalization.yml
  when: normalization


