---
# traffic draining
# 1. Collect current running configs
# 2. Save the running configs on the Ansible Controller /tmp
# 3. library/getList.py script is run.. Creates an interfaces.txt and protocols.txt files
# 4. Ansible tasks run against the data in the 2 files above.

- name: Collect juniper device running configs
  junipernetworks.junos.junos_command:
    commands: show configuration
    display: set
  register: config_output
  ignore_errors: true

# - name: Display task results
#   ansible.builtin.debug:
#     var: config_output

# regex_replace('\r\n', '\n'): Ensures that the configuration is formatted properly with new lines,
# in case the original output contains carriage return and line feed (\r\n).
- name: Set some variables
  ansible.builtin.set_fact:
    formatted_config: "{{ config_output.stdout[0] | regex_replace('\r\n', '\n') }}" # Ensure the config is properly formatted plus set file name
    running_config_file: "{{ tmp_root_dir }}/running-config.txt"
    interfaces_file: "{{ tmp_root_dir }}/interfaces.txt"
    protocols_file: "{{ tmp_root_dir }}/protocols.txt"
  delegate_to: localhost
  ignore_errors: true
  when: config_output["failed"] == false

- name: Save the configuration to the temporary config store
  ansible.builtin.copy:
    content: "{{ formatted_config }}"
    dest: "{{ running_config_file }}"
  delegate_to: localhost
  ignore_errors: true
  when: config_output["failed"] == false

- name: Run library/getList.py
  ansible.builtin.command:
    cmd: "python3 library/getList.py {{ running_config_file }} {{ interfaces_file }} {{ protocols_file }}" # A string that identifies which function to call
  register: script_output

# Read the health-checks commands files and create a list of commands to run
- name: Generate Lists from interfaces.txt and protocols.txt files
  ansible.builtin.set_fact:
    interfaces_list: "{{ lookup('file', '{{ interfaces_file }}').splitlines() }}"
    # protocols_list: "{{ lookup('file', '{{ protocols_file }}').splitlines() }}"
  delegate_to: localhost

# - name: Display lists
#   ansible.builtin.debug:
#     msg: 
#       - "Interfaces ; {{ interfaces_list }}"
#       - "Protocols ; {{ protocol_list }}"
#   delegate_to: localhost
#   ignore_errors: true

- name: Display commands to run
  ansible.builtin.debug:
    msg: 
      - "disable {{ item }}"
  loop: "{{ interfaces_list }}"
  delegate_to: localhost
  ignore_errors: true

# Commands happen from here
# - name: Shut down the listed interfaces
#   junipernetworks.junos.junos_command:       # is this the module to configure/change anything?
#     commands: disable {{ item }}             # Interfaces to be shut down
#   loop: "{{ interfaces_list }}"
#   when: 
#     - interfaces | length > 0
#     - isolation

# - name: Admin up the listed interfaces
#   junipernetworks.junos.junos_command:
#     commands: enable/delete {{ item }}             # Interfaces to be unshut
#   loop: "{{ interfaces_list }}"
#   when: 
#     - interfaces | length > 0
#     - normalization