---
# perform traffic normalization
# git clone of the device config backup repo.
# Commands in post-upgrade-traffic-normalization.cfg are implemented

- name: Clone the config backup git repository
  ansible.builtin.git:
    repo: "{{ git_repo_url }}"
    dest: "{{ tmp_root_dir }}/{{ git_repo_name }}"
    version: "{{ git_repo_branch }}"
    force: yes       # Still clone down and overwrite incase local repo is existing.
  # ignore_errors: true # You want this to fail if errors are there
  environment:
    GIT_SSL_NO_VERIFY: "true"
  run_once: true
  delegate_to: localhost
  ignore_errors: true # You want the role to run end to end

- name:
  ansible.builtin.debug:
    msg: "Traffic normalization tasks ......"
  delegate_to: localhost
